../PE/src/SystemVerilogCSP.sv
../PE/src/PE.sv
../PE/src/depacketizer.sv
../PE/src/split.sv
../PE/src/special_split.sv
../PE/src/priority_mux.sv
../PE/src/copy.sv
../PE/src/copy4.sv
../PE/src/conditional_copy.sv
../PE/src/mac.sv
../PE/src/spike_residue.sv
../PE/src/two_input_adder.sv
../PE/src/merge.sv
../PE/src/packetizer.sv
../router/router_mesh/design/arbiter.sv
../router/router_mesh/design/arbiter_merge.sv
../router/router_mesh/design/arbiter_merge_4in.sv
../router/router_mesh/design/mesh.sv
../router/router_mesh/design/router.sv
./top.tb.sv